### ISSUE TITLE
[Feature Request] Non-URI-encoded Bang

### ISSUE THREAD

**Issue by smhmd** [travis-g/bang#8]
```yaml
ghr:
  description: GitHub Repo
  format: https://github.com/{{{r}}} #r for raw
```
```sh
$ bang ghr travis-g/bang # opens https://github.com/travis-g/bang
```

---

**A suggestion:**
One thing I do in my dmenu script, is that I subtitute `@@` with `xclip -o` (secondary selection) if it holds something. You could consider that. I can think of a configurable `@@` for secondary selection and `@!` for primary selection. Maybe you can think of some other interface.

**Comment by travis-g** [comment]
Based on the title, are you looking to have a way to pass through the query exactly, without any escaping? [`escape_method: 1` for `PASS_THROUGH`](https://github.com/travis-g/bang/blob/master/bang.go#L39-L41) may be what you're looking for. The escape methods are going into the help text/usage info soon.

The default `sourcegraph` bang uses the pass-through option:

```console
% jq .sourcegraph bangs.json  
{
  "description": "Sourcegraph",
  "escape_method": 1,
  "format": "https://sourcegraph.com/{{{s}}}"
}
% ./bang -url sourcegraph github.com/travis-g/bang
https://sourcegraph.com/github.com/travis-g/bang
```

To clarify about your xclip suggestion, are you looking for a way to do multi-parameter/multi-query bangs? Or conditional logic?

**Comment by smhmd** [comment]
> are you looking for a way to do multi-parameter/multi-query bangs? Or conditional logic?

I was thinking of opening an issue about multi-parameter.

The idea is to abstract clipboard in scripts/automation in contexts where `ctrl+v` isn't present like `dmenu`.

In the picture, I have `WebAssembly` selected, hit my keybinding for dmenu, and enter `search terms @@ additional search terms`.

![pic](https://user-images.githubusercontent.com/46059092/74197222-5632df00-4c5f-11ea-928a-033cf9827ab6.png)
This opens `https://www.google.com/search?q=WebAssembly+with+rust`.

similarly, multi-parameters can be abstracted by some sort of delimiter.
```yaml
wa:
  description: Send Whatsapp Message
  format: https://api.whatsapp.com/send?phone={{{s1}}}&text={{{s2}}}
```
![pic](https://user-images.githubusercontent.com/46059092/74197269-719dea00-4c5f-11ea-87f1-a627b3ce1a9f.png)
Opens `https://api.whatsapp.com/send?phone=15551234567&text=okay`.

**Comment by travis-g** [comment]
Multi-param may be simpler with [templates](https://godoc.org/text/template), but I'd have to think on that. You may be able to use a wrapper script:
```yaml
wa:
  description: Send Whatsapp Message
  format: https://api.whatsapp.com/send?{{{s}}}
```
```sh
#!/usr/bin/env sh
printf "phone=%s&text=%s" "$1" "$2" | bang wa -
```
