### ISSUE TITLE
[Feature Request] Default To/Bookmarks

### ISSUE THREAD

**Issue by smhmd** [travis-g/bang#9]
Similar to DuckDuckGo bang's behavior.

```yaml
4g:
  description: 4chan Technology
  format: https://boards.4channel.org/g/catalog#s={{{s}}}
  default: https://boards.4channel.org/g/catalog
```

```zsh
$ bang 4g iem # opens https://boards.4channel.org/g/catalog#s=iem
$ bang 4g # opens https://boards.4channel.org/g/catalog
```
